### PR TITLE
Correct name of member variable m_stbWrapper of class SBTWrapper

### PR DESCRIPTION
**Pull request by AdaDoom3**
I see no obvious reason for the rearrangement of letters in m_stbWrapper - perhaps this was in error?

### CODE REVIEW

**Comment by AdaPlusPlus** [comment]
I will update the PR to have a DCO under my AdaDoom3 account tomorrow.

**Comment by AdaDoom3** [comment]
The DCO has been added.

**Review by mklefrancois — APPROVED** [review]
LGTM

**Comment by NBickford-NV** [comment]
Ah, I removed some large objects from the Git history and it had the side effect of closing this -- sorry about that! I'll merge this in.

**Comment by NBickford-NV** [comment]
Looks like Martin-Karl merged this in earlier as part of https://github.com/nvpro-samples/vk_raytrace/commit/7089fb23aadb0dd398a4d33e2267cf83eca88f1a . Thank you for finding the typo and for making the merge request!

**Pull request closed without merging**
